### PR TITLE
Issue/364/statistics

### PR DESCRIPTION
**Pull request by raintonr**
Few stats for now. Maybe I will add the detail for unknown events if get a chance.

### CODE REVIEW

**Comment by UncleSamSwiss** [comment]
Thanks a lot for the PR. May I ask you to update the changelog in README.md according to https://github.com/AlCalzone/release-script#usage
If you want, please feel free to add yourself as a contributor in the package info.

**Review by UncleSamSwiss — CHANGES_REQUESTED** [review]
Please update the changelog.

**Comment by raintonr** [comment]
@UncleSamSwiss bump?

**Comment by raintonr** [comment]
In fact... wait a sec. Doing a little more testing (graphing values over time) to make sure this is good.

**Comment by raintonr** [comment]
> Doing a little more testing

Yes... that's better :clown_face:

**Pull request merged**
