### PR TITLE
Watch is not allowed in tsconfig

### PR DESCRIPTION
**Pull request by Arcticon**
Fixes UncleSamSwiss/ioBroker.loxone#539

### CODE REVIEW

**Comment by Arcticon** [comment]
@raintonr can i please get a quick review? :)
thanks!

**Comment by raintonr** [comment]
Why did you not move this to 'watchOptions'?

**Comment by Arcticon** [comment]
Because you can not disable watch anymore: https://www.typescriptlang.org/docs/handbook/configuring-watch.html

**Comment by raintonr** [comment]
No worries then.

**Pull request closed without merging**
